Repository modern-agile-team/8term-mini-front, pull requests merged in 2024-07, with the labels that each got.

#4 docs/atomicpattern/#3
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/Router/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
Labels: docs

#9 publish/에러 페이지 퍼블리싱/#8
  src/Router/App.jsx
  src/pages/error/NotFound.jsx
  src/pages/error/styled.js
  src/pages/test.js
Labels: feat, publish 

#10 publish/타이틀아이콘,메인페이지 퍼블리싱/#6
  index.html
  src/components/atomic/Icon/Login.jsx
  src/components/atomic/Icon/Logo.jsx
  src/components/atomic/Icon/Search.jsx
  src/components/atomic/Icon/Title.jsx
  src/components/molecules/LoginSearch.jsx
  src/components/organisms/Header.jsx
  src/components/templates/MainScreen.jsx
  src/index.css
  src/pages/MainPage.jsx
Labels: publish 

#17 repector/에러페이지 폴더 구조 변경/#8
  public/vite.svg
  src/Router/App.jsx
  src/components/page_components/login/InputEmail.jsx
  src/components/page_components/main/LikeButton.jsx
  src/components/page_components/main/Login.jsx
  src/components/page_components/main/LoginSearch.jsx
  src/components/page_components/main/Logo.jsx
  src/components/page_components/main/MainScreen.jsx
  src/components/page_components/main/MovieContainer.jsx
  src/components/page_components/main/MovieContent.jsx
  src/components/page_components/main/MovieName.jsx
  src/components/page_components/main/MovieNameYear.jsx
  src/components/page_components/main/MoviePhoto.jsx
  src/components/page_components/main/MovieYear.jsx
  src/components/page_components/main/Search.jsx
  src/components/page_components/main/Title.jsx
  src/components/page_components/main/mainStyled.js
  src/components/public_components/Header.jsx
  src/pages/login/LoginPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/styled.js
Labels: refactor 

#24 publish/회원가입 오타 수정/#19
  src/Router/App.jsx
  src/components/page_components/resister/RegisterForm.jsx
  src/components/page_components/resister/RegisterStyled.js
  src/pages/login/LoginPage.jsx
  src/pages/resister/RegisterPage.jsx
  src/pages/resister/RegisterPageStyled.js
Labels: publish 
